// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: namenode.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NameNode service

func NewNameNodeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NameNode service

type NameNodeService interface {
	AddFileMetaData(ctx context.Context, in *AddReq, opts ...client.CallOption) (*Result, error)
	UpdateFileBlockMetaData(ctx context.Context, in *UpdateReq, opts ...client.CallOption) (*Result, error)
}

type nameNodeService struct {
	c    client.Client
	name string
}

func NewNameNodeService(name string, c client.Client) NameNodeService {
	return &nameNodeService{
		c:    c,
		name: name,
	}
}

func (c *nameNodeService) AddFileMetaData(ctx context.Context, in *AddReq, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.name, "NameNode.addFileMetaData", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeService) UpdateFileBlockMetaData(ctx context.Context, in *UpdateReq, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.name, "NameNode.UpdateFileBlockMetaData", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NameNode service

type NameNodeHandler interface {
	AddFileMetaData(context.Context, *AddReq, *Result) error
	UpdateFileBlockMetaData(context.Context, *UpdateReq, *Result) error
}

func RegisterNameNodeHandler(s server.Server, hdlr NameNodeHandler, opts ...server.HandlerOption) error {
	type nameNode interface {
		AddFileMetaData(ctx context.Context, in *AddReq, out *Result) error
		UpdateFileBlockMetaData(ctx context.Context, in *UpdateReq, out *Result) error
	}
	type NameNode struct {
		nameNode
	}
	h := &nameNodeHandler{hdlr}
	return s.Handle(s.NewHandler(&NameNode{h}, opts...))
}

type nameNodeHandler struct {
	NameNodeHandler
}

func (h *nameNodeHandler) AddFileMetaData(ctx context.Context, in *AddReq, out *Result) error {
	return h.NameNodeHandler.AddFileMetaData(ctx, in, out)
}

func (h *nameNodeHandler) UpdateFileBlockMetaData(ctx context.Context, in *UpdateReq, out *Result) error {
	return h.NameNodeHandler.UpdateFileBlockMetaData(ctx, in, out)
}
