// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: datanode.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DataNode service

func NewDataNodeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DataNode service

type DataNodeService interface {
	UploadFileBlock(ctx context.Context, in *UploadArgs, opts ...client.CallOption) (*Result, error)
}

type dataNodeService struct {
	c    client.Client
	name string
}

func NewDataNodeService(name string, c client.Client) DataNodeService {
	return &dataNodeService{
		c:    c,
		name: name,
	}
}

func (c *dataNodeService) UploadFileBlock(ctx context.Context, in *UploadArgs, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.name, "DataNode.UploadFileBlock", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataNode service

type DataNodeHandler interface {
	UploadFileBlock(context.Context, *UploadArgs, *Result) error
}

func RegisterDataNodeHandler(s server.Server, hdlr DataNodeHandler, opts ...server.HandlerOption) error {
	type dataNode interface {
		UploadFileBlock(ctx context.Context, in *UploadArgs, out *Result) error
	}
	type DataNode struct {
		dataNode
	}
	h := &dataNodeHandler{hdlr}
	return s.Handle(s.NewHandler(&DataNode{h}, opts...))
}

type dataNodeHandler struct {
	DataNodeHandler
}

func (h *dataNodeHandler) UploadFileBlock(ctx context.Context, in *UploadArgs, out *Result) error {
	return h.DataNodeHandler.UploadFileBlock(ctx, in, out)
}
